### ISSUE TITLE
Testsuite setup errors

### ISSUE THREAD

**Issue by kynzie** [sphinx-contrib/cookiecutter#3]
**Describe the bug**
When I used cookiecutter and check the testsuite, I found two different problems.

When running `tox` locally:

1. `sphinx` dependency is not pulled into `tox` environment which raise the following exception: `ImportError: Error importing plugin "sphinx.testing.fixtures": No module named 'sphinx'` 

2. `flake8` reports an error in [cookiecutter/{{cookiecutter.project_name}}/sphinxcontrib/{{cookiecutter.package_name}}/__init__.py](https://github.com/sphinx-contrib/cookiecutter/blob/d02c0d662e3d54a3a1abbd98d1b4074df9eb0b1c/%7B%7Bcookiecutter.project_name%7D%7D/sphinxcontrib/%7B%7Bcookiecutter.package_name%7D%7D/__init__.py#L23): 
`# type: (Sphinx) -> Dict[unicode, Any]`, unicode is not recognized and raise a F821 error

More logs in the attached file: [testsuite_errors.log](https://github.com/sphinx-contrib/cookiecutter/files/4602893/testsuite_errors.log)

**To Reproduce**
1. Create a virtualenv: `python -m venv env`
2. Source it: `source env/bin/activate`
3. Install `cookiecutter`: `pip install cookiecutter`
4. Create a dummy extension using `cookiecutter`: `cookiecutter https://github.com/sphinx-contrib/cookiecutter.git`
2. Install `tox` and run it

**Expected behavior**
I expect the testsuite to fail because there is no tests.

**Environment info**
- OS: Linux (Archlinux)
- Python version: 3.8.2
- cookiecutter version: master (d02c0d662e3d54a3a1abbd98d1b4074df9eb0b1c)

**Additional context**
As described above, I used a python virtual environment.

**Comment by stephenfin** [comment]
Resolves in #4
